name: Push to Master

on:
  push:
    branches: [master]
    paths: ['cea/**', 'conda-lock.yml']

jobs:
  test:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Run tests
        shell: bash -l {0}
        run: |
          cea test --type unittest
          cea test --type integration
